source 'https://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'hubbubbly', :path => '../'

# for testing the hubbubbly gem!

gem 'rspec-rails', '~> 2.6'
gem 'factory_girl_rails', '~> 1.2'
gem 'guard', '~> 0.5'
gem 'guard-bundler', '~> 0.1.3'
gem 'guard-rspec', '~> 0.4'
gem 'capybara'
gem 'faker'
gem 'database_cleaner', '0.5.2'
gem 'simplecov', '~> 0.4'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'
